
name: Deploy Nightly
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Deploy Nightly
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nim
        uses: iffy/install-nim@v5
        with:
          version: binary:2.0.2

      - if: matrix.os == 'windows-latest'
        name: Check for commits today (win)
        id: check_commits_win
        shell: pwsh
        run: |
          # Get the current date in YYYY-MM-DD format
          $today = (Get-Date).ToString("yyyy-MM-dd")

          # Get the list of commits for today
          $commits = git log --since="$today 00:00:00" --until="$today 23:59:59" --pretty=format:"%H"

          # If there are no commits, set the output to 'false'
          if (-not $commits) {
            echo "::set-output name=commits_present::false"
          } else {
            echo "::set-output name=commits_present::true"
          }
      - if: matrix.os == 'ubuntu-latest'
        name: Check for commits today (linux)
        id: check_commits_linux
        shell: bash
        run: |
          # Get the current date in YYYY-MM-DD format
          today=$(date +%Y-%m-%d)

          # Get the list of commits for today
          commits=$(git log --since="$today 00:00:00" --until="$today 23:59:59" --pretty=format:"%H")

          # If there are no commits, set the output to 'false'
          if [ -z "$commits" ]; then
            echo "commits_present=false" >> $GITHUB_OUTPUT
          else
            echo "commits_present=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Build if Commits Present (win)
        if: steps.check_commits.outputs.commits_present == 'true' && matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          echo "Commits were found for today. Running build script..."
          ./build.ps1

      - name: Run Build if Commits Present (linux)
        if: steps.check_commits.outputs.commits_present == 'true' && matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          echo "Commits were found for today. Running build script..."
          ./build.sh

      - name: Upload Build Artifact (win)
        if: steps.check_commits.outputs.commits_present == 'true' && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: lychee-build-windows
          path: lychee-build-win.zip

      - name: Upload Build Artifact (linux)
        if: steps.check_commits.outputs.commits_present == 'true' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: lychee-build-linux
          path: lychee-build-linux-x64.zip

